#!/bin/bash

if [ "$1" != "" ]
then
        cd $1
fi

if [ -e ".git" ]
then
        echo "found git repository in $1, scanning for branches..."
        for branch in `git branch | awk '{print $2}'`
        do
                echo "found branch $branch"
        done

fi
for i in `ls *`
do
        if [ -d $i ]
        then
                pull_everything $i
        fi
done


